services:
  mysql-db:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/mysql:8.0
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  node-app:
    build: .
    container_name: my_node_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql-db
      DB_USER: root
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - mysql-db

volumes:
  mysql_data:
