import type { AllowedTable } from './tables.js';

/** 数据表中文名 */
export const TABLE_LABELS: Record<AllowedTable, string> = {
  account_transactions: '账户流水',
  accounts: '账户',
  admin_users: '管理员',
  app_meta: '应用元数据',
  app_settings: '应用设置',
  cash_flow_expense_lines: '现金流支出项',
  cash_flow_holdings: '现金流持仓',
  cash_flow_incomes: '现金流收入',
  cash_flow_profile: '现金流配置',
  daily_review_journal: '每日复盘',
  earned_rewards: '已获得奖励',
  finance_account_types: '财务账户类型',
  finance_accounts: '财务账户',
  finance_flow_categories: '财务流水分类',
  finance_transactions: '财务交易',
  frog_completion_events: '青蛙完成事件',
  goal_dimensions: '目标维度',
  habit_check_ins: '习惯打卡',
  habit_contexts: '习惯场景',
  habits: '习惯',
  health_records: '健康记录',
  memo_dimensions: '备忘录维度',
  memos: '备忘录',
  persona_portrait_cache: '人物画像缓存',
  project_categories: '项目分类',
  projects: '项目',
  recipe_categories: '食谱分类',
  recipe_items: '食谱',
  review_columns: '复盘栏目',
  review_dimensions: '复盘维度',
  savings_plan_deposits: '储蓄存入记录',
  savings_plans: '储蓄计划',
  task_categories: '任务分类',
  task_execution_events: '任务执行事件',
  task_items: '任务子项',
  tasks: '任务',
  user_desired_skills: '期望技能',
  user_skill_items: '技能条目',
  user_skills_meta: '技能元数据',
  user_weaknesses: '待提升项',
  users: '用户',
  visions: '愿景',
  weekly_review_journal: '每周复盘',
  wish_items: '心愿单',
};

/** 字段通用中文名 */
export const COLUMN_LABELS: Record<string, string> = {
  id: 'ID',
  key: '键名',
  slug: '标识',
  name: '名称',
  title: '标题',
  username: '账号',
  password: '密码',
  password_hash: '密码哈希',
  phone: '手机号',
  value: '值',
  value_json: '配置JSON',
  body: '内容',
  note: '备注',
  notes: '备注',
  description: '描述',
  detail: '详情',
  type: '类型',
  status: '状态',
  amount: '金额',
  balance: '余额',
  currency: '货币',
  category: '分类',
  category_id: '分类ID',
  category_label: '分类标签',
  account_id: '账户ID',
  account_no: '账号编号',
  account_type: '账户类型',
  parent_id: '父级ID',
  project_id: '项目ID',
  task_id: '任务ID',
  habit_id: '习惯ID',
  user_id: '用户ID',
  wish_item_id: '心愿ID',
  savings_plan_id: '储蓄计划ID',
  flow_category_id: '流水分类ID',
  dimension_id: '维度ID',
  linked_task_id: '关联任务ID',
  parent_task_id: '父任务ID',
  source_id: '来源ID',
  source_type: '来源类型',
  source_title: '来源标题',
  reward_kind: '奖励类型',
  label: '标签',
  tag: '标签',
  icon: '图标',
  icon_key: '图标键',
  tone: '色调',
  context: '场景',
  gender: '性别',
  lifestyle: '生活方式',
  goal: '目标',
  workout_days: '训练日',
  rest_days: '休息日',
  birthday: '生日',
  height: '身高',
  weight: '体重',
  age: '年龄',
  avatar_uri: '头像',
  reference_image_uri: '参考图片',
  finished_image_uri: '成品图片',
  source_image_uri: '来源图片',
  happened_at: '发生时间',
  earned_at: '获得时间',
  redeemed_at: '兑换时间',
  completed_at: '完成时间',
  due_date: '截止日期',
  record_date: '记录日期',
  record_date_ymd: '记录日期',
  week_start_ymd: '周起始日期',
  cache_date_ymd: '缓存日期',
  assigned_ymd: '分配日期',
  start_date: '开始日期',
  end_date: '结束日期',
  created_at: '创建时间',
  updated_at: '更新时间',
  sync_status: '同步状态',
  extra_data: '扩展数据',
  payload_json: '缓存数据',
  sort_order: '排序',
  is_done: '是否完成',
  is_builtin: '是否内置',
  is_liability: '是否负债',
  sign_rule: '符号规则',
  priority: '优先级',
  count: '次数',
  price: '价格',
  desire_level: '渴望程度',
  reason: '理由',
  bucket: '分类桶',
  quadrant: '象限',
  principal: '本金',
  inflow: '流入',
  outflow: '流出',
  necessary_expenses: '必要支出',
  unnecessary_expenses: '非必要支出',
  target_passive_income: '目标被动收入',
  target_months: '目标月数',
  seed_version: '种子版本',
  target_amount: '目标金额',
  transaction_type: '交易类型',
  ai_comment: 'AI点评',
  ai_evaluation: 'AI评价',
  ai_suggestions: 'AI建议',
  ai_review_at: 'AI评审时间',
  ai_coaching: 'AI教练建议',
  last_evaluation: '最近评估',
  last_suggestions: '最近建议',
  last_ai_at: '最近AI时间',
  last_overall_suggestions: '最近综合建议',
  last_profile_analysis: '最近画像分析',
  target_level: '目标等级',
  action: '操作',
  task_title: '任务标题',
  placeholder: '占位提示',
  scope: '范围',
  track_kind: '轨道类型',
  direction: '方向',
  bg_option_idx: '背景选项',
  hydration: '饮水量',
  target_hydration: '目标饮水量',
  protein: '蛋白质',
  target_protein: '目标蛋白质',
  carbohydrate: '碳水化合物',
  target_carbohydrate: '目标碳水',
  sodium: '钠',
  target_sodium: '目标钠',
  quick_add_key: '快捷添加键',
  intake_display_title: '摄入标题',
  intake_ai_comment: '摄入AI点评',
  ingredients_json: '食材JSON',
  steps_json: '步骤JSON',
  section_summary: '本周总结',
  section_plans: '本周计划',
  section_reflect: '本周反思',
  section_learnings: '本周收获',
  section_next_week: '下周安排',
  execution_score: '执行评分',
  adjust_tasks: '调整任务',
  adjust_savings: '调整储蓄',
  adjust_plans: '调整计划',
  inbox_entered_at: '进入收件箱时间',
};

/** 表级字段中文名覆盖 */
export const TABLE_COLUMN_LABELS: Partial<
  Record<AllowedTable, Partial<Record<string, string>>>
> = {
  tasks: {
    category_id: '任务分类ID',
  },
  projects: {
    category_id: '项目分类ID',
  },
};

export function getTableLabel(table: string): string {
  return TABLE_LABELS[table as AllowedTable] ?? table;
}

export function getColumnLabel(table: string, column: string): string {
  const tableOverrides = TABLE_COLUMN_LABELS[table as AllowedTable];
  return tableOverrides?.[column] ?? COLUMN_LABELS[column] ?? column;
}

export function buildColumnMeta(table: string, columns: string[]) {
  return columns.map((name) => ({
    name,
    label: getColumnLabel(table, name),
  }));
}
